language: ruby
cache: bundler
rvm:
- 2.7.2
install:
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  fqdn: blog.vepo.dev
  on:
    branch: source
