name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - source # or master before October 2020

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: actions/checkout@v2
        with:
          ref: source
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2
        with:
          target_branch: master
          target_path: /
          keep_history: true
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          MY_GITHUB_SECRET: ${{ secrets.MY_GITHUB_SECRET }}
